- pipework
Create utility function to provide a consistent means to test what external commands are installed.
Use the POSIX `type` utility, which is a builtin in many shells, instead of the popular, but non-standard `which`.
Signed-off-by: Michael A. Smith <msmith3@ebay.com>
> Utility function to test what is installed

- pipework
Quotes misplacement causes `ovs-vsctl: : missing column name`
> Fix VLAN tag passing to ovs-vsctl

- pipework
Maybe I missed something, but it doesn't look as though the current schema for local interface name generation is chosen for any specific reason. This option allows the local interface name to be set to something meaningful (for instance the name of the container to which the interface belongs).
I haven't built in any error checking (i.e. checking if the interface to be specified already exists), this could be done in a further step if this change is seen as useful.
> Allow local interface name to be specified

- pipework
Some times /sys/fs/cgroup/devices/lxc/{GUESTNAME}/tasks  file is empty
so this part of code doesn't work correct
```
NSPID=$(head -n 1 "$(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks")
```
and it causes the errors like this:
```
Could not find a process inside container {GUESTNAME}.
```
or
```
There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "pipework", "vlxcbr0", "{GUESTNAME}", "192.168.2.104/24"]
```
I don't sure which is the root cause of the problem, but this approach works for me
> it is an alternative way to get the pid

- README.md
Tiny text fix, but was bugging me!
> DHCP option separator is colon, not semi-colon

- README.md
`Am79C973` is the type id for **PCnet-FAST III**
> Setup Adapter Type in Vagrantfile

- README.md
- pipework
This prevents moving the selected IPoIB interface from the host to the
container. Instead, create a child interface and only move that
interface.
The code is based on the code @hookenz wrote (see [pull request](https://github.com/jpetazzo/pipework/pull/108)).
> Add support for child IPoIB interfaces

- README.md
- pipework
Adds support for generated mac address with uniqueness.
If the mac address follows the pattern with `U:<string>`, then it will use `<string>` to generate a unique mac address in the Locally Administered range. This allows people to have unique and repeatable mac addresses, without needing to manually manage and enter them.
Most common use case, of course, is to use hostname.
> Enable support for a custom generated mac address

- pipework
When determining whether a port needs to be added to an ovs switch, pipework
first greps to see if a port by that name is on the switch, in which case it
skips adding the port.
The check uses a grep which also matches against ports which contain the name
to be added as a substring, erroneously determining that the port is already on
the switch.
This change tightens the grep to look for exactly the desired port name.
> Fix loose grep match

- README.md
- pipework
Per this Issue https://github.com/jpetazzo/pipework/issues/181 , give users option to keep udhcpc and dhclient around to manage the lease. Also updated README.md to describe how it works and how to manage it.
> Create option to keep dhcp clients alive so they can manage (and renew) leases even after pipework exits

- README.md
- pipework
Add support for route. Anything after "pipework <CONTAINER_ID> route" will be passed to `ip route` run inside the container.
> Add support for routes

- README.md
- pipework
I've found in a lot of experiments that I need to directly assign an interface to a container, both with SR-IOV and with normal physical interfaces.  This change adds an optional --direct-phys first argument to skip the creation of a macvlan.  If someone is working on a getopts version of this script, I'd be happy to add it there.
> Option to namespace physical and SR-IOV interfaces without using macvlan

- pipework
This aims to fix a bug: when you run pipework assigning an IPv4 address and afterwards assign an IPv6 address, pipework removes the original IPv4 default route instead of the IPv6 one.
A new optional argument (-a 4 or -a 6) allows one to specify the type of address to be added.
> Added support for ip family option (IPv4 or IPv6) when addressing statically

- README.md
- pipework
This is a simple commit that clones the functionality of `pipework route` for `pipework rule`, which passes args to `ip rule` instead of `ip route`.
I used this for configuring multiple NICs in a docker container and assigning each their own default gateway. For every NIC, I create a network. At container startup I connect it to one of the networks. After startup I connect it to the other networks. Then I add a route table for each NIC and set the default route separately for each one.
In my case this allows me to create proxy containers that can bind to multiple interfaces and forward traffic on multiple outbound IPs (e.g. using squidproxy).
> Add "pipework rule" command for passing args to "ip rule" ; add "pipework tc" for passing args to "tc"

- pipework
Pipework doesn't populate the openvswitch database with any information
about the pipework interface creation. This makes it difficult to glean
any information about the container to which an interface is assigned.
This patch adds the bridge, interface name, container ID and vlan to
the database so other tools can query it.
This patch was originally designed to help tools like @dreamcat4's
docker-pipework image clean up these interfaces when the container is started
with something like 'docker run --rm' (with modifications).
> Adding metadata to openvswitch database.

- pipework
By the way, would it be better to use `nsenter -un` instead of `ip netns exec`? `nsenter -un` will enter both network namespace and UTS namespace, while `ip netns exec` only enter network namespace.
> fix: sh doesn't support substr syntax

- README.md
- pipework
When using commands such as:
```
pipework --direct-phys eth0 -i iface1 <docker_pid> 0/0
```
The physical interface eth0 gets renamed as iface1 in the host context and the behavior is not idempotent.
Adding support to specify the interface through its MAC address, such as:
```
pipework --direct-phys mac:00:f3:15:4a:42:c8 -i iface1 <docker_pid> 0/0
```
This may be useful when the physical interface to "pipework" is eth0 (might already exist in a "usual" docker container).
> Allow to specify host interface via mac address

- pipework
LXC 3.1.0 mounts two entries in cgroups now instead of one. The code expected
one entry to be returned at all times.
Added a simple check for this particular case.
> Fix lxc 3.1.0

- pipework
Executing `echo "" | wc -l` results in 1, causing the code to expect
a cgroup matching the guest name when there is no such cgroup.
Check explicitly for empty output in the results of searching
the cgroup.
> Fix docker container lookup

- pipework
When trying to move a wireless interface using --direct-phys option, the command is failing with "RTNETLINK answers: Invalid argument"
This issue is caused by the following command : ip link set "$GUEST_IFNAME" netns "$NSPID"
To fix that we need to use iw iso ip
> Use iw command to set the namespace of a wireless interface

- pipework
1- Add a workaround for cgroupv2 working only for docker.
2- Remove output of "command -v" from the console traces.
3- Truncate the length of GUEST_IFNAME as "ip link add ..." command doe not supports names with size higher than 15 chars.
> Add workaround for cgroupv2 + Minure fixes

- pipework
In Ubuntu the default shell points to `dash` rather than `bash`. As such, this substitution (line 375):
```
GUEST_IFNAME=${GUEST_IFNAME:0:15}
```
returns an error as that syntax is not supported by `dash`. Setting the shebang do `/bin/bash` fixes this.
> Change shebang to /bin/bash
